webtalk_init -webtalk_dir C:/Users/fs09911/Desktop/CA-Labs/Lab11/Lab11_Verilog/Lab11_Verilog.sim/sim_1/behav/xsim/xsim.dir/tb_TopLevelProcessor_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Mar 24 12:54:47 2026" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d589e2c2-c50f-4dac-8c07-135e1db9a5a4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "0e08b3de8b2241d2bd5e79ae2b20ab5c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "7" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "13th Gen Intel(R) Core(TM) i5-13500" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2496 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8720_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3446329182 -regid "" -xml C:/Users/fs09911/Desktop/CA-Labs/Lab11/Lab11_Verilog/Lab11_Verilog.sim/sim_1/behav/xsim/xsim.dir/tb_TopLevelProcessor_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/fs09911/Desktop/CA-Labs/Lab11/Lab11_Verilog/Lab11_Verilog.sim/sim_1/behav/xsim/xsim.dir/tb_TopLevelProcessor_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/fs09911/Desktop/CA-Labs/Lab11/Lab11_Verilog/Lab11_Verilog.sim/sim_1/behav/xsim/xsim.dir/tb_TopLevelProcessor_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
